<a href="https://colab.research.google.com/github/Nov05/Google-Colaboratory/blob/master/20230910_sklearn_CountVectorize%2C_csr_matrix%2C_np_matrix_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
documents = ['This is a document.', 'This is another document.']
vectorizer = CountVectorizer(token_pattern='\w+')
vectorizer.fit(documents)
new_document = 'This is a new document.'
new_document_vector = vectorizer.transform([new_document])
print(type(new_document_vector))
new_document_vector

<class 'scipy.sparse._csr.csr_matrix'>


<1x5 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [ ]:
import numpy as np
display(new_document_vector.todense())
display(new_document_vector.todense().astype(np.ndarray))

matrix([[1, 0, 1, 1, 1]])

matrix([[1, 0, 1, 1, 1]], dtype=object)

In [ ]:
import pandas as pd
url = "https://docs.google.com/spreadsheets/d/1uuVKGW0aZggso42VoTw4ftUtJyDnzrIsMqwc-lsu4Qw/export?format=csv"
df = pd.read_csv(url)
df.sample(1)

text_id                                          full_text  \
3445  EC2758A5B74E  Dear School board,\n\nWhy does a student's edu...   

      cohesion  syntax  vocabulary  phraseology  grammar  conventions  
3445       5.0     5.0         4.5          5.0      5.0          4.5

In [ ]:
docs = df['full_text']
vectorizer = CountVectorizer(vocabulary=["i", "I"], lowercase=False, token_pattern=r"(?u)\b\w\b")
docs_vec = vectorizer.fit_transform(docs)
display(docs_vec)
display(docs_vec.todense())

<3911x2 sparse matrix of type '<class 'numpy.int64'>'
	with 4190 stored elements in Compressed Sparse Row format>

matrix([[ 0,  1],
        [22,  0],
        [ 0,  1],
        ...,
        [ 0,  3],
        [ 0,  0],
        [ 0,  2]])

In [ ]:
np.sum(docs_vec, axis=1)

matrix([[ 1],
        [22],
        [ 1],
        ...,
        [ 3],
        [ 0],
        [ 2]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(np.sum(docs_vec, axis=1))
## TypeError: np.matrix is not supported. Please convert to a numpy array with np.asarray.
## For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
## Note: It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.

TypeError: ignored

In [ ]:
display(np.sum(docs_vec, axis=1).A)
display(np.sum(docs_vec, axis=1).A1)

array([[ 1],
       [22],
       [ 1],
       ...,
       [ 3],
       [ 0],
       [ 2]])

array([ 1, 22,  1, ...,  3,  0,  2])

In [ ]:
scaler.fit_transform(np.sum(docs_vec, axis=1).A)

array([[-0.59334438],
       [ 1.66255633],
       [-0.59334438],
       ...,
       [-0.37849669],
       [-0.70076822],
       [-0.48592053]])